apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx 
    tier: deployment
spec:
  # modify replicas according to your case
  replicas: 1
  selector: # These labels are used to find the pods
    matchLabels:
      app: nginx 
      tier: deployment
  template: # pod-definition
    metadata:
      labels:
        app: nginx 
        tier: deployment
    spec:
      containers:
      - name: nginx
        # image: nginx:stable-alpine3.21-perl 
        image: nginx
        ports:
        - containerPort: 80 
--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-loadbalancer
spec: 
  type: LoadBalancer
  selector: 
   app: nginx 
   tier: deployment
  ports:
  - protocol: TCP 
    port: 80 #service port 
    targetPort: 80 #container port 