apiVersion: v1
kind: Pod
metadata:
  name: taint
spec:
# list of containers
  containers:
  - name: taint-pod
    image: nginx
    ports:
    - containerPort: 80

--- 

apiVersion: v1
kind: Pod
metadata:
  name: toleration
spec:
# list of containers
  containers:
  - name: taint-pod
    image: nginx
    ports:
    - containerPort: 80
  tolerations:
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"