apiVersion: v1
kind: Pod
metadata:
  name: with-affinity-preferred-weight
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - devops1
      - weight: 50
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop1
  containers:
  - name: with-node-affinity
    image: nginx
