apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod1
  labels: 
    name: affinity-pod1
spec:
# list of containers
  containers:
  - name: affinity-pod
    image: nginx
    ports:
    - containerPort: 80
  
--- 

apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - affinity-pod1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: affinity-pod2
    image: nginx
