apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  # namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |
     filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
      output:
        elasticsearch:
          hosts: ["elasticsearch:9200"]
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx 
    tier: deployment
spec:
  # modify replicas according to your case
  replicas: 3
  selector: # replica labels 
    matchLabels:
      app: nginx 
      tier: deployment
  template: # pod-definition
    metadata:
      labels:
        app: nginx 
        tier: deployment
    spec:
      containers:
      - name: nginx # nginx container
        image: nginx:mainline-alpine3.22
        ports:
        - containerPort: 80 
        volumeMounts:
        - name: nginx-logs 
          mountPath: /var/log/nginx 

      - name: filebeat-sidecar # sidecar container
        image: docker.elastic.co/beats/filebeat:7.17.3
        volumeMounts: 
        - name: nginx-logs 
          mountPath: /var/log/nginx 
        
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          readOnly: true  

      volumes: 
      - name: nginx-logs #Creating the Empty Volume
        emptyDir: {}

      - name: filebeat-config #Creating the Volume from ConfigMap
        configMap: 
          name: filebeat-config 
          items: 
          - key: filebeat.yml
            path: filebeat.yml 