apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05b73fcd151fc0950
---

# Claiming the Volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: efs-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

--- 
# Pod definition
apiVersion: v1
kind: Pod
metadata:
  name: nginx-efs-static
  labels: 
    demo: efs-static
spec:
  containers:
  - name: nginx-efs-static
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  nodeSelector: 
    zone: 1d
  volumes: #Creating the volume from pv claim configuration
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static-claim

--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: efs-static-pv-lb
spec: 
  type: LoadBalancer
  selector: 
   demo: efs-static 
  ports:
  - protocol: TCP 
    port: 80 #service port 
    targetPort: 80 #container port 