---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-roboshop
  resources:
    requests:
      storage: 5Gi
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-efs-dynamic
  labels:
    app: nginx 
    tier: deployment
spec:
  # modify replicas according to your case
  replicas: 3
  selector: # These labels are used to find the pods
    matchLabels:
      demo: efs-dynamic
  template: # pod-definition
    metadata:
      labels:
        demo: efs-dynamic
    spec:
      containers:
      - name: nginx
        # image: nginx:stable-alpine3.21-perl 
        image: nginx:mainline-alpine3.22
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
      volumes: #Creating the volume from pv claim configuration
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-dynamic-claim

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: efs-dynamic-lb
spec: 
  type: LoadBalancer
  selector: 
   demo: efs-dynamic
  ports:
  - protocol: TCP 
    port: 80 #service port 
    targetPort: 80 #container port 