apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs 
  labels:
    app: nginx 
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector: # These labels are used to find the pods
    matchLabels:
      app: nginx 
      tier: frontend
  template: # pod-definition
    metadata:
      labels:
        app: nginx 
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: stable-alpine3.21-perl
