apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx 
    tier: deployment
spec:
  # modify replicas according to your case
  replicas: 3
  selector: # replica labels 
    matchLabels:
      app: nginx 
      tier: deployment
  template: # pod-definition
    metadata:
      labels:
        app: nginx 
        tier: deployment
    spec:
      containers:
      - name: nginx
        # image: nginx:stable-alpine3.21-perl 
        image: nginx:mainline-alpine3.22
        ports:
        - containerPort: 80 
