apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  # namespace: roboshop
spec:
# list of containers
  containers:
  - name: hello-pod
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  
  - name: almalinux-pod
    image: almalinux:9
    ports:
    - containerPort: 8080
    command: ["sleep", "300"]
