apiVersion: v1 
kind: Pod 
metadata: 
  name: pod-secret 
spec: 
  containers: 
  - name: pod-secret 
    image: nginx 
    ports: 
    - containerPort: 80 
    envFrom: 
    - secretRef: 
        name: devops-secrets 